[2024-03-11T03:00:37.245+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_penguins_data_to_mysql.load_penguins_data_task manual__2024-03-11T03:00:33.643749+00:00 [queued]>
[2024-03-11T03:00:37.261+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_penguins_data_to_mysql.load_penguins_data_task manual__2024-03-11T03:00:33.643749+00:00 [queued]>
[2024-03-11T03:00:37.262+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2024-03-11T03:00:37.283+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_penguins_data_task> on 2024-03-11 03:00:33.643749+00:00
[2024-03-11T03:00:37.290+0000] {standard_task_runner.py:57} INFO - Started process 72 to run task
[2024-03-11T03:00:37.295+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_penguins_data_to_mysql', 'load_penguins_data_task', 'manual__2024-03-11T03:00:33.643749+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/load_data_dag.py', '--cfg-path', '/tmp/tmp0cp8yc73']
[2024-03-11T03:00:37.298+0000] {standard_task_runner.py:85} INFO - Job 259: Subtask load_penguins_data_task
[2024-03-11T03:00:37.375+0000] {task_command.py:410} INFO - Running <TaskInstance: load_penguins_data_to_mysql.load_penguins_data_task manual__2024-03-11T03:00:33.643749+00:00 [running]> on host 79cfc012d0d6
[2024-03-11T03:00:37.785+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_penguins_data_to_mysql' AIRFLOW_CTX_TASK_ID='load_penguins_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T03:00:33.643749+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-11T03:00:33.643749+00:00'
[2024-03-11T03:00:37.787+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data_dag.py", line 13, in load_data_to_mysql
    data = pd.read_csv("/opt/airflow/data/penguins_lter.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/penguins_lter.csv'
[2024-03-11T03:00:37.805+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=load_penguins_data_to_mysql, task_id=load_penguins_data_task, execution_date=20240311T030033, start_date=20240311T030037, end_date=20240311T030037
[2024-03-11T03:00:37.826+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 259 for task load_penguins_data_task ([Errno 2] No such file or directory: '/opt/airflow/data/penguins_lter.csv'; 72)
[2024-03-11T03:00:37.843+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-03-11T03:00:37.869+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
