[2024-03-11T03:05:01.545+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_penguins_data_to_mysql.load_penguins_data_task manual__2024-03-11T03:04:57.762506+00:00 [queued]>
[2024-03-11T03:05:01.560+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_penguins_data_to_mysql.load_penguins_data_task manual__2024-03-11T03:04:57.762506+00:00 [queued]>
[2024-03-11T03:05:01.561+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2024-03-11T03:05:01.582+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_penguins_data_task> on 2024-03-11 03:04:57.762506+00:00
[2024-03-11T03:05:01.588+0000] {standard_task_runner.py:57} INFO - Started process 81 to run task
[2024-03-11T03:05:01.593+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_penguins_data_to_mysql', 'load_penguins_data_task', 'manual__2024-03-11T03:04:57.762506+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/load_data_dag.py', '--cfg-path', '/tmp/tmpf_ck4cjq']
[2024-03-11T03:05:01.597+0000] {standard_task_runner.py:85} INFO - Job 292: Subtask load_penguins_data_task
[2024-03-11T03:05:01.677+0000] {task_command.py:410} INFO - Running <TaskInstance: load_penguins_data_to_mysql.load_penguins_data_task manual__2024-03-11T03:04:57.762506+00:00 [running]> on host e376f9348fca
[2024-03-11T03:05:02.077+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_penguins_data_to_mysql' AIRFLOW_CTX_TASK_ID='load_penguins_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-03-11T03:04:57.762506+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-11T03:04:57.762506+00:00'
[2024-03-11T03:05:02.080+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_data_dag.py", line 13, in load_data_to_mysql
    data = pd.read_csv("/opt/airflow/data/penguins_lter.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '/opt/airflow/data/penguins_lter.csv'
[2024-03-11T03:05:02.097+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=load_penguins_data_to_mysql, task_id=load_penguins_data_task, execution_date=20240311T030457, start_date=20240311T030501, end_date=20240311T030502
[2024-03-11T03:05:02.115+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 292 for task load_penguins_data_task ([Errno 21] Is a directory: '/opt/airflow/data/penguins_lter.csv'; 81)
[2024-03-11T03:05:02.145+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2024-03-11T03:05:02.172+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
